# Generated by Django 4.2 on 2024-07-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_spot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('req_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-req_time'],
            },
        ),
    ]
